### ISSUE TITLE
Allow more than one sentence

### ISSUE THREAD

**Issue by heikowagner** [heikowagner/generalized-semantic-regression#7]
In the current implementation only one sentence is allowed, but in theorie L sentences are possible:

Idea:
If L sentences  should be used 
- we fit L BERT Models
- these model share the same parameter (syiamese BERT)

**Comment by MarkWClements** [comment]
Hello @heikowagner, can you elaborate here? If I have a matrix of NxD where N is the number of sentences and  D is the dimensionality of the Bert model (i.e. 768) do you mean that the code can't take the entire NxD matrix?

Also, is it possible to use RISKBert with a pre-trained SBERT model like all-mpnet-base-v2 rather than the pre-trained BERT models?

Lastly, if I have the sentence embeddings saved from the SBERT model as floats in the form of a Nx768 matrix, however, I do not have the positional tokens from the embeddings saved (the CLS, SEP and EOS token). Can I still feed this matrix directly into RISKBert or do I need to pass the original text so that RISKBert has access to these?

**Comment by heikowagner** [comment]
Hi @MarkWClements ,
I strongly recommand to experiment with the simulation:
https://github.com/heikowagner/generalized-semantic-regression/blob/main/RiskBERT/simulation/simulation.py


> Hello @heikowagner, can you elaborate here? If I have a matrix of NxD where N is the number of sentences and D is the dimensionality of the Bert model (i.e. 768) do you mean that the code can't take the entire NxD matrix?

I'm not 100% sure if I understood the Question. If N is the number of observations with one sentence per observation than this is possible. Best practice is to prepare a Dataset like here https://github.com/heikowagner/generalized-semantic-regression/blob/main/RiskBERT/simulation/data_functions.py#L58 where a list of sentences is passed to the trainer. If you have N observations with L (may vary) sentences this is not possible atm. I plan to implement the possibility to pass a list of lists.

> 
> Also, is it possible to use RISKBert with a pre-trained SBERT model like all-mpnet-base-v2 rather than the pre-trained BERT models?

yes this should is possible as long as the used model is inherited from the BertPreTrainedModel class. Just change this line https://github.com/heikowagner/generalized-semantic-regression/blob/main/RiskBERT/simulation/simulation.py#L26 

> 
> Lastly, if I have the sentence embeddings saved from the SBERT model as floats in the form of a Nx768 matrix, however, I do not have the positional tokens from the embeddings saved (the CLS, SEP and EOS token). Can I still feed this matrix directly into RISKBert or do I need to pass the original text so that RISKBert has access to these?

Original Text will be better, it is not implemented to pass the embeddings. However, your idea is in fact related to the freeze scenario. If you somehow manage to put your embeddings here https://github.com/heikowagner/generalized-semantic-regression/blob/main/RiskBERT/models.py#L64 it will work. In fact if you do not plan to retain the BERT you can just copy-paste this part https://github.com/heikowagner/generalized-semantic-regression/blob/main/RiskBERT/models.py#L61-L70 and use pytorch to fit the net.
